import { spatialTransform } from './spatial.js';
const search=document.querySelector('#global-search'),results=document.querySelector('#search-results'),searchAction=document.querySelector('#search-action'),nav=document.querySelector('.navlinks'),menu=document.querySelector('.menu');
const items=[...document.querySelectorAll('a[href], .feature-card, .semester')].filter((item)=>!item.closest('header'));
const searchable=(item)=>`${item.dataset.search||''} ${item.textContent||''}`.replace(/\s+/g,' ').trim();
function renderSearchResults(matches){results.replaceChildren();if(!matches.length){const p=document.createElement('p');p.textContent='No indexed result. Try a subject, semester, topic, PYQ, or note.';results.append(p);return}for(const item of matches){const link=document.createElement('a'),strong=document.createElement('strong'),meta=document.createElement('span');link.href=item.getAttribute('href')||'#';strong.textContent=item.dataset.search||item.querySelector('h2,h3')?.textContent?.trim()||searchable(item).slice(0,60);meta.textContent=item.textContent.trim();link.append(strong,meta);results.append(link)}}
function runSearch(){const q=(search?.value||'').trim().toLowerCase();if(!results)return;if(!q){results.hidden=true;results.replaceChildren();return}renderSearchResults(items.filter((item)=>searchable(item).toLowerCase().includes(q)).slice(0,8));results.hidden=false}
search?.addEventListener('input',runSearch);search?.addEventListener('keydown',(event)=>{if(event.key==='Escape'){search.value='';runSearch();search.blur()}if(event.key==='Enter')runSearch()});searchAction?.addEventListener('click',runSearch);menu?.addEventListener('click',()=>nav?.classList.toggle('open'));document.querySelectorAll('a[href^="#"]').forEach((anchor)=>anchor.addEventListener('click',()=>nav?.classList.remove('open')));
const world=document.querySelector('#bytecore-world'),spatial=world?.querySelector('[data-spatial-world]'),reduce=window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches;
if(spatial&&!reduce){const apply=(x,y)=>{const t=spatialTransform(x,y);spatial.style.transform=`rotateX(${t.rotateX}deg) rotateY(${t.rotateY}deg) translate3d(${t.translateX}px,${t.translateY}px,0)`};const reset=()=>apply(.5,.5);const move=(cx,cy)=>{const r=spatial.parentElement.getBoundingClientRect();if(r.width&&r.height)apply((cx-r.left)/r.width,(cy-r.top)/r.height)};spatial.addEventListener('pointermove',(e)=>move(e.clientX,e.clientY));spatial.addEventListener('pointerleave',reset);spatial.addEventListener('pointercancel',reset);spatial.addEventListener('touchmove',(e)=>{const t=e.touches[0];if(t)move(t.clientX,t.clientY)},{passive:true});spatial.addEventListener('touchend',reset,{passive:true})}
const sections=[...document.querySelectorAll('.section')];if('IntersectionObserver'in window&&!reduce){const observer=new IntersectionObserver((entries)=>entries.forEach((entry)=>{if(entry.isIntersecting)entry.target.classList.add('is-visible')}),{threshold:.14,rootMargin:'0px 0px -8% 0px'});sections.forEach((section)=>observer.observe(section))}else sections.forEach((section)=>section.classList.add('is-visible'));
(async()=>{if(!world||reduce||!window.WebGLRenderingContext)return;try{const{initByteCoreWorld}=await import('./three-world.js');initByteCoreWorld(world)}catch(error){world.dataset.threeFallback='true';console.info('ByteCore 3D runtime unavailable; CSS world retained.',error?.message||error)}})();
