import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { academicNode, cameraMotion, qualityProfile } from './three-world-core.js';

const LABELS=['SYLLABUS','SUBJECTS','UNITS','TOPICS','NOTES','PRACTICE','PYQs','AI TUTOR','WORKSPACE'];

function material(color,roughness=.22,metalness=.55,opacity=1){return new THREE.MeshPhysicalMaterial({color,roughness,metalness,transmission:opacity<1?.35:0,transparent:opacity<1,opacity,clearcoat:.8,clearcoatRoughness:.14})}
function labelSprite(text){const canvas=document.createElement('canvas');canvas.width=320;canvas.height=88;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,320,88);ctx.fillStyle='rgba(3,12,16,.86)';ctx.strokeStyle='rgba(139,225,232,.7)';ctx.lineWidth=2;ctx.roundRect(5,8,310,62,20);ctx.fill();ctx.stroke();ctx.font='800 22px Inter,Arial,sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#F4FBFC';ctx.fillText(text,160,39);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthWrite:false}));sprite.scale.set(1.42,.39,1);sprite.position.set(0,-.55,.05);return sprite}
function createCore(){const group=new THREE.Group();const shell=new THREE.Mesh(new THREE.IcosahedronGeometry(1.08,3),material('#2EACB9',.12,.8));const inner=new THREE.Mesh(new THREE.OctahedronGeometry(.58,2),material('#8BE1E8',.08,.65));const ring=new THREE.Mesh(new THREE.TorusGeometry(1.34,.018,12,96),new THREE.MeshBasicMaterial({color:'#ffffff',transparent:true,opacity:.7}));ring.rotation.x=Math.PI*.42;group.add(shell,inner,ring);return group}

export function initByteCoreWorld(root){
 if(!root||!root.ownerDocument)return{destroy(){}};
 const reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches??false;const profile=qualityProfile(window.innerWidth,reduced);
 const scene=new THREE.Scene();scene.fog=new THREE.FogExp2('#03090d',.045);const camera=new THREE.PerspectiveCamera(profile.mobile?34:28,1,.1,100);camera.position.set(0,.15,profile.mobile?8.4:7.1);
 const renderer=new THREE.WebGLRenderer({antialias:!profile.mobile,alpha:true,powerPreference:profile.mobile?'default':'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,profile.pixelRatio));renderer.setClearColor('#03090d',0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.domElement.setAttribute('aria-hidden','true');renderer.domElement.style.cssText='width:100%;height:100%;display:block;touch-action:none;';
 scene.add(new THREE.HemisphereLight('#dfffff','#03151a',2.5));const key=new THREE.DirectionalLight('#ffffff',4);key.position.set(4,5,6);scene.add(key);const fill=new THREE.PointLight('#2EACB9',10,16);fill.position.set(-3,-1,4);scene.add(fill);const rim=new THREE.PointLight('#B8E66B',6,12);rim.position.set(3,2,-1);scene.add(rim);
 const world=new THREE.Group();scene.add(world);const core=createCore();world.add(core);
 const satellites=[];const count=profile.satellites;
 for(let i=0;i<count;i++){const p=academicNode(i,count);const group=new THREE.Group();group.position.set(p.x,p.y,p.z);const size=i%3===0?.27:.19;const mesh=new THREE.Mesh(i%3===0?new THREE.IcosahedronGeometry(size,1):new THREE.SphereGeometry(size,18,18),material(i%2?'#ffffff':'#B8E66B',i%2?.18:.12,.4,i%4===0?.84:1));group.add(mesh);const label=labelSprite(LABELS[i]);label.scale.multiplyScalar(profile.mobile?.75:1);group.add(label);satellites.push({group,mesh,phase:i*.73});world.add(group)}
 const lineMaterial=new THREE.LineBasicMaterial({color:'#8BE1E8',transparent:true,opacity:.18});satellites.forEach(s=>world.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,0,0),s.group.position.clone()]),lineMaterial)));
 const pointer={x:0,y:0,targetX:0,targetY:0,down:false,lastX:0,lastY:0,hover:false};
 const onPointerMove=e=>{if(pointer.down){pointer.targetY+=(e.clientX-pointer.lastX)*.006;pointer.targetX+=(e.clientY-pointer.lastY)*.006;pointer.lastX=e.clientX;pointer.lastY=e.clientY;return}const r=root.getBoundingClientRect();if(!r.width||!r.height)return;const m=cameraMotion((e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height,profile.mobile);pointer.targetX=m.x*Math.PI/18;pointer.targetY=m.y*Math.PI/18};
 const onPointerDown=e=>{pointer.down=true;pointer.lastX=e.clientX;pointer.lastY=e.clientY;root.setPointerCapture?.(e.pointerId)};const onPointerUp=e=>{pointer.down=false;root.releasePointerCapture?.(e.pointerId)};const onEnter=()=>{pointer.hover=true};const onLeave=()=>{pointer.hover=false;if(!pointer.down){pointer.targetX=0;pointer.targetY=0}};
 root.addEventListener('pointermove',onPointerMove);root.addEventListener('pointerdown',onPointerDown);root.addEventListener('pointerup',onPointerUp);root.addEventListener('pointercancel',onPointerUp);root.addEventListener('pointerenter',onEnter);root.addEventListener('pointerleave',onLeave);
 const resize=()=>{const w=Math.max(1,root.clientWidth),h=Math.max(1,root.clientHeight);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};const observer=new ResizeObserver(resize);observer.observe(root);resize();root.replaceChildren(renderer.domElement);
 const clock=new THREE.Clock();let frame=0;const animate=()=>{frame=requestAnimationFrame(animate);const t=clock.getElapsedTime();pointer.x+=(pointer.targetX-pointer.x)*.055;pointer.y+=(pointer.targetY-pointer.y)*.055;const idle=profile.animate?(pointer.hover?t*.12:t*.045):0;world.rotation.x=pointer.x+(profile.animate?Math.sin(t*.18)*.025:0);world.rotation.y=pointer.y+idle;core.rotation.x=profile.animate?t*.1:0;core.rotation.y=profile.animate?t*.14:0;satellites.forEach((s,i)=>{if(!profile.animate)return;const bob=Math.sin(t*.55+s.phase)*.05;s.mesh.position.y=bob;s.mesh.rotation.x=t*(.16+i*.008);s.mesh.rotation.y=t*(.2+i*.01);s.group.children[1].quaternion.copy(camera.quaternion)});renderer.render(scene,camera)};animate();
 return{destroy(){cancelAnimationFrame(frame);observer.disconnect();root.removeEventListener('pointermove',onPointerMove);root.removeEventListener('pointerdown',onPointerDown);root.removeEventListener('pointerup',onPointerUp);root.removeEventListener('pointercancel',onPointerUp);root.removeEventListener('pointerenter',onEnter);root.removeEventListener('pointerleave',onLeave);renderer.dispose();scene.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>{m.map?.dispose();m.dispose()})}})}}
}
